<a href="https://colab.research.google.com/github/VaishnaviTyagi23/Machine_Learning/blob/main/3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays(w.r.t.list and python):


1.   Allows several Mathematical Operations.
2.   Faster operations






In [1]:
import numpy as np # numpy is library

List vs Numpy - Time Taken
(time is another library)

In [2]:
from time import process_time
#time taken by a particular process

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]#for loop which puts values from 1 to 10,0000

start_time = process_time()#to measure time taken by this process

python_list = [i+5 for i in python_list]#add 5 to all values in the list

end_time = process_time()

print(end_time - start_time)
# time in sec-> 1millisec

0.0015475700000000536


Time taken by numpy array

In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0013646490000001066


#Numpy Arrays

In [6]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
#same in numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)#ndarray is n-dimensional array

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape # gives no. of rows and columns here only 4 as its 1-D

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape #rows,columns

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)#5*4 array with 5 value
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.80055982 0.70197234 0.29942169 0.39827012]
 [0.1736815  0.88243336 0.34936586 0.45868811]
 [0.51468898 0.47041513 0.37082725 0.57961755]]


In [20]:
# random integer values array within a specific range(10 to 100)
c = np.random.randint(10,100,(3,5))
print(c)

[[14 61 46 59 70]
 [47 32 55 93 64]
 [38 52 27 75 64]]


In [21]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,3)
print(d)

[10. 20. 30.]


In [22]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [23]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [24]:
c = np.random.randint(10,90,(5,5))#make array
print(c)

[[35 81 58 46 21]
 [62 59 39 11 61]
 [82 20 22 45 85]
 [84 64 51 49 14]
 [19 83 74 63 26]]


In [25]:
# array dimension
print(c.shape)

(5, 5)


In [26]:
# number of dimensions
print(c.ndim)

2


In [27]:
# number of elements in an array
print(c.size)

25


In [28]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array


In [29]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[7 0 8]
 [9 8 2]
 [6 0 2]]
[[17 10 10]
 [13 14 19]
 [13 18 14]]


In [32]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[24 10 18]
 [22 22 21]
 [19 18 16]]
[[-10 -10  -2]
 [ -4  -6 -17]
 [ -7 -18 -12]]
[[119   0  80]
 [117 112  38]
 [ 78   0  28]]
[[0.41176471 0.         0.8       ]
 [0.69230769 0.57142857 0.10526316]
 [0.46153846 0.         0.14285714]]


In [33]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [34]:
print(a)
print(b)

[[9 4 5]
 [2 8 5]
 [6 0 6]]
[[12 12 13]
 [19 18 19]
 [11 13 15]]


In [35]:
print(np.add(a,b))#another way
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 16 18]
 [21 26 24]
 [17 13 21]]
[[ -3  -8  -8]
 [-17 -10 -14]
 [ -5 -13  -9]]
[[108  48  65]
 [ 38 144  95]
 [ 66   0  90]]
[[0.75       0.33333333 0.38461538]
 [0.10526316 0.44444444 0.26315789]
 [0.54545455 0.         0.4       ]]


Array Manipulation

In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 7 2]
 [8 0 5]]
(2, 3)


In [37]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 8]
 [7 0]
 [2 5]]
(3, 2)


In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 6]
 [3 3 7]]
(2, 3)


In [39]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 3]
 [1 3]
 [6 7]]
(3, 2)


In [40]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 3 1]
 [6 9 8]]
(2, 3)


In [41]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 3]
 [1 6]
 [9 8]]
(3, 2)
